# Generated by Django 2.2.13 on 2021-06-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone2',
        ),
        migrations.AddField(
            model_name='orders',
            name='amount',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
